name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
on:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  my_job:
    name: ubuntu-latest
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

